-- ScreenShare / Rise
-- Reconstrução do antigo supabase.sql a partir do código público do repositório:
-- https://github.com/cardosodevs/ScreenShare
--
-- Execute no Supabase Dashboard > SQL Editor.
--
-- Observação:
-- Este arquivo reproduz o comportamento observado em app.js/server.js.
-- Como o supabase.sql original não está no repositório, nomes de constraints,
-- índices e alguns detalhes de tipagem são reconstruídos.

begin;

-- =========================================================
-- TABELA: rise_rooms
-- =========================================================

create table if not exists public.rise_rooms (
    code                text primary key,
    title               varchar(80) not null default 'Sessão Rise',
    host_name           varchar(80) not null,
    host_token_hash     text not null,
    password_hash       text null,
    status              text not null default 'waiting',
    locked              boolean not null default false,
    closed              boolean not null default false,
    expires_at          timestamptz not null,
    created_at          timestamptz not null default now()
);

create index if not exists rise_rooms_expires_at_idx
    on public.rise_rooms (expires_at);

create index if not exists rise_rooms_active_idx
    on public.rise_rooms (code, expires_at)
    where closed = false;


-- =========================================================
-- TABELA: rise_logs
-- =========================================================

create table if not exists public.rise_logs (
    id                  bigint generated by default as identity primary key,
    room_code           text not null,
    actor_name          varchar(80) not null default 'Sistema',
    event_type          varchar(60) not null,
    details             varchar(500) null,
    created_at          timestamptz not null default now(),

    constraint rise_logs_room_code_fkey
        foreign key (room_code)
        references public.rise_rooms(code)
        on delete cascade
);

create index if not exists rise_logs_room_created_idx
    on public.rise_logs (room_code, created_at desc);


-- =========================================================
-- RLS
-- =========================================================

alter table public.rise_rooms enable row level security;
alter table public.rise_logs enable row level security;

-- Não liberamos SELECT direto em rise_rooms:
-- a função rise_room_public expõe apenas os campos seguros,
-- sem host_token_hash/password_hash.

drop policy if exists "rise_rooms_public_insert" on public.rise_rooms;

create policy "rise_rooms_public_insert"
on public.rise_rooms
for insert
to anon, authenticated
with check (
    length(trim(code)) > 0
    and expires_at > now()
    and closed = false
);

-- Logs são usados diretamente pelo frontend:
-- sb.from('rise_logs').insert(...)
-- sb.from('rise_logs').select('*').eq('room_code', ...)
--
-- Restringimos a leitura/escrita a salas existentes e não expiradas.

drop policy if exists "rise_logs_public_select" on public.rise_logs;
drop policy if exists "rise_logs_public_insert" on public.rise_logs;

create policy "rise_logs_public_select"
on public.rise_logs
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.rise_rooms r
        where r.code = rise_logs.room_code
          and r.closed = false
          and r.expires_at > now()
    )
);

create policy "rise_logs_public_insert"
on public.rise_logs
for insert
to anon, authenticated
with check (
    exists (
        select 1
        from public.rise_rooms r
        where r.code = rise_logs.room_code
          and r.closed = false
          and r.expires_at > now()
    )
);


-- =========================================================
-- RPC: rise_create_room
-- =========================================================
--
-- Frontend:
-- sb.rpc('rise_create_room', {
--   p_code,
--   p_title,
--   p_host_name,
--   p_host_token_hash,
--   p_password_hash,
--   p_expires_at
-- })
--
-- Retorno esperado: boolean.

create or replace function public.rise_create_room(
    p_code text,
    p_title text,
    p_host_name text,
    p_host_token_hash text,
    p_password_hash text,
    p_expires_at timestamptz
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    v_code text;
begin
    v_code := upper(trim(p_code));

    if v_code = '' then
        return false;
    end if;

    if p_expires_at is null or p_expires_at <= now() then
        return false;
    end if;

    insert into public.rise_rooms (
        code,
        title,
        host_name,
        host_token_hash,
        password_hash,
        status,
        locked,
        closed,
        expires_at
    )
    values (
        v_code,
        left(coalesce(nullif(trim(p_title), ''), 'Sessão Rise'), 80),
        left(coalesce(p_host_name, ''), 80),
        p_host_token_hash,
        p_password_hash,
        'waiting',
        false,
        false,
        p_expires_at
    );

    return true;

exception
    when unique_violation then
        return false;
end;
$$;


-- =========================================================
-- RPC: rise_room_public
-- =========================================================
--
-- Retorna somente informações públicas.
-- O app espera data?.[0].
--
-- Campos confirmados pelo servidor substituto:
-- code, title, host_name, status, locked, closed,
-- password_required, expires_at.

create or replace function public.rise_room_public(
    p_code text
)
returns table (
    code text,
    title text,
    host_name text,
    status text,
    locked boolean,
    closed boolean,
    password_required boolean,
    expires_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
    select
        r.code,
        r.title::text,
        r.host_name::text,
        r.status,
        r.locked,
        r.closed,
        (r.password_hash is not null) as password_required,
        r.expires_at
    from public.rise_rooms r
    where r.code = upper(trim(p_code))
      and r.closed = false
      and r.expires_at > now()
    limit 1;
$$;


-- =========================================================
-- RPC: rise_check_password
-- =========================================================
--
-- O navegador já envia SHA-256 da senha.
-- Esta função apenas compara o hash recebido com o salvo.

create or replace function public.rise_check_password(
    p_code text,
    p_password_hash text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(
        (
            select
                r.password_hash is not null
                and r.password_hash = p_password_hash
            from public.rise_rooms r
            where r.code = upper(trim(p_code))
              and r.closed = false
              and r.expires_at > now()
            limit 1
        ),
        false
    );
$$;


-- =========================================================
-- RPC: rise_host_action
-- =========================================================
--
-- Ações observadas:
-- title  -> altera título
-- lock   -> true/false
-- close  -> encerra a sala e define status='closed'
-- status -> altera status
--
-- Só executa quando o hash do token do host confere.

create or replace function public.rise_host_action(
    p_code text,
    p_host_token_hash text,
    p_action text,
    p_value text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    v_code text := upper(trim(p_code));
    v_ok boolean;
begin
    select exists (
        select 1
        from public.rise_rooms r
        where r.code = v_code
          and r.host_token_hash = p_host_token_hash
          and r.closed = false
          and r.expires_at > now()
    )
    into v_ok;

    if not v_ok then
        return false;
    end if;

    case p_action
        when 'title' then
            if nullif(trim(coalesce(p_value, '')), '') is not null then
                update public.rise_rooms
                set title = left(trim(p_value), 80)
                where code = v_code;
            end if;

        when 'lock' then
            update public.rise_rooms
            set locked = lower(coalesce(p_value, 'false')) = 'true'
            where code = v_code;

        when 'close' then
            update public.rise_rooms
            set closed = true,
                status = 'closed'
            where code = v_code;

        when 'status' then
            if nullif(trim(coalesce(p_value, '')), '') is not null then
                update public.rise_rooms
                set status = trim(p_value)
                where code = v_code;
            end if;

        else
            return false;
    end case;

    return true;
end;
$$;


-- =========================================================
-- PERMISSÕES DAS RPCs
-- =========================================================

revoke all on function public.rise_create_room(text,text,text,text,text,timestamptz) from public;
revoke all on function public.rise_room_public(text) from public;
revoke all on function public.rise_check_password(text,text) from public;
revoke all on function public.rise_host_action(text,text,text,text) from public;

grant execute on function public.rise_create_room(text,text,text,text,text,timestamptz)
    to anon, authenticated;

grant execute on function public.rise_room_public(text)
    to anon, authenticated;

grant execute on function public.rise_check_password(text,text)
    to anon, authenticated;

grant execute on function public.rise_host_action(text,text,text,text)
    to anon, authenticated;


-- O frontend acessa rise_logs diretamente.
grant select, insert on public.rise_logs to anon, authenticated;

-- O fallback de criação usa INSERT direto em rise_rooms.
grant insert on public.rise_rooms to anon, authenticated;

-- Sequence/identity do rise_logs.
grant usage, select on all sequences in schema public to anon, authenticated;


-- =========================================================
-- LIMPEZA DE SALAS EXPIRADAS (opcional)
-- =========================================================
--
-- O server.js alternativo remove salas expiradas e seus logs.
-- A FK com ON DELETE CASCADE já remove os logs quando a sala
-- for apagada. Esta função pode ser chamada por cron/pg_cron.

create or replace function public.rise_purge_expired_rooms()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    v_count integer;
begin
    delete from public.rise_rooms
    where expires_at <= now();

    get diagnostics v_count = row_count;
    return v_count;
end;
$$;

revoke all on function public.rise_purge_expired_rooms() from public;


-- =========================================================
-- REALTIME
-- =========================================================
--
-- O app usa Supabase Realtime para Presence/Broadcast,
-- não precisa publicar rise_rooms/rise_logs em postgres_changes.
--
-- Os canais usados são públicos:
-- topic: rise-<CODIGO>
--
-- Presence/Broadcast são configurados no cliente.

commit;